<a href="https://colab.research.google.com/github/sivakumarmadimi/mgpvtltd/blob/main/pytorchpractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
np.array([10,12,13])

array([10, 12, 13])

In [4]:
np.add(10,12)

22

In [5]:
import torch as tc

In [6]:
print(tc.__version__)

2.5.1+cu121


In [7]:
print(tc.cuda.is_available())

False


In [9]:
vb=tc.tensor([10,12,13])

In [10]:
print(vb)

tensor([10, 12, 13])


In [13]:
vc=vb+tc.tensor([10,13,14])

In [14]:
print(vc)


tensor([20, 25, 27])


In [30]:
vx=tc.tensor([12,16,15])

In [31]:
vd=tc.cat([vc,vx],dim=0)

In [26]:
print(vd)

tensor([20, 25, 27, 12, 16, 15])


In [35]:
twoDim=tc.tensor([[1,2,3],[1,5,6]])

In [36]:
twoDim.dim()

2

In [44]:
vf=twoDim.divide(vc)

In [45]:
vf

tensor([[0.0500, 0.0800, 0.1111],
        [0.0500, 0.2000, 0.2222]])